const frases = [
    "¡Vamos, (nombre_de_jugador)! 🚀 ¡Que se sienta la energía! 🔥",
    "¡Dale con todo, (nombre_de_jugador)! 💥 Que no se diga que te achicás. 😎",
    "¡Arriba, (nombre_de_jugador)! 🎉 ¡Este momento es todo tuyo! 🕺",
    "¡No hay excusas, (nombre_de_jugador)! 🎲 La ronda te llama. 📣",
    "¡Atenti, (nombre_de_jugador)! 👀 No te duermas, la diversión no espera. 🎭",
    "¡Jugale al éxito, (nombre_de_jugador)! 🎯 ¡Vos podés! 💪",
    "¡Vamos con fe, (nombre_de_jugador)! 🌟 El mundo es de quienes se animan. 🍻",
    "¡Te toca a vos, (nombre_de_jugador)! 🃏 A romperla, che. 🧨",
    "¡Ojo, (nombre_de_jugador)! 👁️ Que esta es tu chance. 💫",
    "¡Demostrales, (nombre_de_jugador)! 💃 ¡Acá se juega fuerte! 🤟",
    "¡Estás en el centro del escenario, (nombre_de_jugador)! 🎤 A brillar. ✨",
    "¡No arrugues, (nombre_de_jugador)! 💣 ¡Metéle garra! 🦾",
    "¡A ponerse la 10, (nombre_de_jugador)! ⚽ ¡La ronda lo pide! 📢",
    "¡Cuidado con el crack, (nombre_de_jugador)! 🤩 ¡Viene con todo! 🚀",
    "¡Que ruede el dado, (nombre_de_jugador)! 🎲 ¡La suerte te sonríe! 😏",
    "¡A ver si la clavás al ángulo, (nombre_de_jugador)! ⚡ ¡Dale sin miedo! 😜",
    "¡Es tu turno, (nombre_de_jugador)! 🕰️ ¡Ponete a la altura del juego! 👑",
    "¡Que no te tiemble el pulso, (nombre_de_jugador)! 🃏 Vos la tenés clara. 🔥",
    "¡Dale sin drama, (nombre_de_jugador)! 🎬 ¡Se juega a fondo! 🍺",
    "¡Movete, (nombre_de_jugador)! 💃 La mesa está caliente. 🔥",
    "¡Metele onda, (nombre_de_jugador)! 🌈 Este desafío es pan comido. 🍰",
    "¡Rompe el hielo, (nombre_de_jugador)! ❄️ ¡Estás al mando! 🧊",
    "¡A ver si te la bancás, (nombre_de_jugador)! 😏 ¡Con actitud todo se logra! 💪",
    "¡Es ahora o nunca, (nombre_de_jugador)! ⏳ ¡Sacudite la fiaca! 🥳",
    "¡Piedra libre para vos, (nombre_de_jugador)! 🕹️ ¡Dejá tu marca! 🌟",
    "¡La birra lo pide, (nombre_de_jugador)! 🍺 ¡Jugá como un campeón! 🏆",
    "¡A brillar, (nombre_de_jugador)! 🌟 ¡El spotlight es tuyo! 🎇",
    "¡No aflojes, (nombre_de_jugador)! 🛠️ ¡Jugá con todo! 💯",
    "¡Vamos, (nombre_de_jugador)! 💥 ¡Acá no hay lugar para la tibieza! 🧊",
    "¡Todo el power, (nombre_de_jugador)! ⚡ ¡Que se sienta tu nivel! 🚀",
    "¡Llegó tu momento, (nombre_de_jugador)! 🎯 ¡No hay marcha atrás! 😜",
    "¡Con facha y actitud, (nombre_de_jugador)! 😎 ¡A romperla en esta ronda! 🎲",
    "¡Ojo que es tu jugada, (nombre_de_jugador)! 🧐 ¡Atacá sin piedad! 💣",
    "¡Te eligió el destino, (nombre_de_jugador)! 🔮 ¡No lo desaproveches! 💪",
    "¡Vamos, fenómeno, (nombre_de_jugador)! 🎩 ¡Hacé magia en el juego! ✨",
    "¡Hoy sos protagonista, (nombre_de_jugador)! 🎬 ¡Que se note! 🌟",
    "¡No te me escondas, (nombre_de_jugador)! 👀 ¡La ronda te aclama! 🔥",
    "¡Metéle gas, (nombre_de_jugador)! ⛽ ¡A romperla! 💥",
    "¡No hay presión, (nombre_de_jugador)! 😅 ¡Pero todos te están mirando! 👀",
    "¡A dejar la timidez, (nombre_de_jugador)! 🎉 ¡Es tu show! 😏",
    "¡Activá modo crack, (nombre_de_jugador)! 🕹️ ¡Esto está que arde! 🔥",
    "¡Atenti con (nombre_de_jugador)! 🎭 ¡Que viene a llevarse todo! 🏆",
    "¡Dejate de pavadas, (nombre_de_jugador)! 🤣 ¡Jugá como se debe! 🎲",
    "¡Te toca, (nombre_de_jugador)! 🚦 ¡Encendé motores y jugá! 🚗",
    "¡Metele onda, (nombre_de_jugador)! 😄 ¡Que nadie se quede dormido! 🛎️",
    "¡Ahora sí, (nombre_de_jugador)! 💥 ¡Este desafío es tuyo! 🏹",
    "¡Vamos, (nombre_de_jugador)! 💃 ¡Que no se diga que sos tímido/a! 😏",
    "¡Al ruedo, (nombre_de_jugador)! 🐂 ¡Que esta ronda la ganás vos! 🏆",
    "¡Dejate de joder, (nombre_de_jugador)! 🎉 ¡A divertirse como corresponde! 🍻",
    "¡Toda la actitud, (nombre_de_jugador)! 🌟 ¡La mesa necesita tu magia! 🪄",
    "¡Vamos, (nombre_de_jugador)! 🍻 Si no lo hacés, ya sabés lo que toca... ¡A brindar! 🥂",
    "¡Dale, (nombre_de_jugador)! 🎯 No aflojés ahora, que después te toca chupar. 🍺",
    "¡Atenti, (nombre_de_jugador)! 😜 O cumplís el reto o la birra te espera. 🍻",
    "¡Vos podés, (nombre_de_jugador)! 🦾 Pero si no... ¡Al fondo blanco! 🥃",
    "¡No arrugues, (nombre_de_jugador)! 💥 ¡El vaso ya está preparado! 🍷",
    "¡Reto aceptado o trago tomado, (nombre_de_jugador)! 🎲 Vos elegís. 😏",
    "¡Vamos con todo, (nombre_de_jugador)! 🤩 Que nadie quiere ver tu vaso vacío. 🍺",
    "¡Esta es fácil, (nombre_de_jugador)! 💪 Si no la hacés, ya sabés: ¡a beber! 🥤",
    "¡Decidite, (nombre_de_jugador)! 🎭 ¿Te animás o la botella te llama? 🍾",
    "¡Firme ahí, (nombre_de_jugador)! 🧨 Que el castigo te espera si fallás. 🍸",
    "¡No te achiques, (nombre_de_jugador)! 😈 La ronda tiene sed. 🍻",
    "¡Dale, (nombre_de_jugador)! 🥴 ¡Cumplí el reto antes de quedar doblado! 🤪",
    "¡Estás en la mira, (nombre_de_jugador)! 🎯 ¡O jugás o tomás! 🍹",
    "¡Con todo, (nombre_de_jugador)! 💣 Que el fondo blanco no te asuste. 🥃",
    "¡Vos decidís, (nombre_de_jugador)! 🎬 ¿Hacés el reto o te rendís al trago? 🍷",
    "¡No hay salida, (nombre_de_jugador)! 🚪 ¡O jugás o brindás por la derrota! 🍻",
    "¡Te toca, (nombre_de_jugador)! 🕺 Si no cumplís, el vaso manda. 🥤",
    "¡Dale valor, (nombre_de_jugador)! 💪 Que el alcohol no perdona a los tibios. 🍺",
    "¡Vamos, (nombre_de_jugador)! 🌟 Jugátela o salud con todos. 🥂",
    "¡Ojo, (nombre_de_jugador)! 👁️ El reto te llama y la botella también. 🍾",
    "¡Cumplilo, (nombre_de_jugador)! 🎲 ¡Que nadie quiere verte tan mareado! 🌀",
    "¡Es tu turno, (nombre_de_jugador)! 🥳 ¡El juego no perdona a los flojos! 🍻",
    "¡Metéle onda, (nombre_de_jugador)! 🌈 Que los tragos están al acecho. 🍸",
    "¡A ver qué hacés, (nombre_de_jugador)! 🃏 ¡Si fallás, el vaso te espera! 🥃",
    "¡Toda la actitud, (nombre_de_jugador)! 💥 Pero si no podés... ¡A beber! 🍺",
    "¡No hay excusas, (nombre_de_jugador)! 🚀 ¡Reto o trago, elegí bien! 😎",
    "¡La ronda te mira, (nombre_de_jugador)! 👀 ¡No la defraudes! 🍹",
    "¡Jugátela, (nombre_de_jugador)! 🎯 ¡O la botella va a por vos! 🍾",
    "¡No te caigas ahora, (nombre_de_jugador)! 💪 ¡El fondo blanco no es tan malo! 🥴",
    "¡Vamos, crack, (nombre_de_jugador)! 😜 ¡O cumplís o tomás! 🎲",
    "¡Ponele onda, (nombre_de_jugador)! 🤩 ¡O quedás fuera con un fondo! 🍻",
    "¡Es fácil, (nombre_de_jugador)! 🕹️ ¡Pero si te rendís, el castigo es líquido! 🍺",
    "¡Hacé lo tuyo, (nombre_de_jugador)! 🌟 ¡No dejes que te ganen los tragos! 🍷",
    "¡Vamos con huevos, (nombre_de_jugador)! 💥 ¡La copa te está esperando! 🥃",
    "¡La mesa pide show, (nombre_de_jugador)! 🎭 ¡O tragás! 🍹",
    "¡No te me caigas, (nombre_de_jugador)! 💣 ¡El desafío o el vaso, elegí! 🍺",
    "¡Toda tuya, (nombre_de_jugador)! 🏆 Si no cumplís, el brindis es doble. 🍻",
    "¡Dale, (nombre_de_jugador)! 🧨 ¡Es esto o darle al vaso! 🍸",
    "¡La ronda tiene sed, (nombre_de_jugador)! 🥤 ¡No la hagas esperar! 🕰️",
    "¡Ponete la 10, (nombre_de_jugador)! ⚽ ¡Jugá bien o brindá bien! 🍺",
    "¡Que no tiemble, (nombre_de_jugador)! 🥴 El reto es sencillo, el trago no. 🍻",
    "¡Reto cumplido o vaso vacío, (nombre_de_jugador)! 🏹 Vos tenés la última palabra. 🥃",
    "¡Es hora de jugártela, (nombre_de_jugador)! 🎰 ¡La botella sonríe si fallás! 🍾",
    "¡A romperla o a beberla, (nombre_de_jugador)! 💃 La elección es tuya. 🍷",
    "¡Esta no te la podés perder, (nombre_de_jugador)! 🤩 ¡Cumplí o a brindar! 🥂",
    "¡Jugá sin miedo, (nombre_de_jugador)! 🕹️ ¡El vaso es solo para los perdedores! 🍸",
    "¡Es ahora, (nombre_de_jugador)! 🎯 ¡Reto fácil o tragos difíciles! 🥃",
    "¡A demostrar de qué estás hecho, (nombre_de_jugador)! 💪 ¡Si no... salud! 🍻",
    "¡Atento, (nombre_de_jugador)! 🎲 Si fallás, los tragos no perdonan. 🍺",
    "¡El desafío es todo tuyo, (nombre_de_jugador)! 🕺 ¡No dejes que te gane el alcohol! 🍷",
    "¡A romperla, (nombre_de_jugador)! 🔥 Pero si no... ¡Fondo blanco! 🥃"

];