const retos = [
    "Por turnos deben decir cada uno una letra para formar una palabra real; quien termine la palabra se salva. El que corte la palabra o no forme ninguna, pierde.",
    "Por turnos deben nombrar un personaje de 'Los Simpson'. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben nombrar un color. Quien repita o se quede sin ideas, pierde. No cuentan el Blanco ni el Negro.",
    "Por turnos deben nombrar una moneda extranjera. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir 'me voy a hacer popó' de una forma creativa, indirecta o divertida. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir 'qué olor a pedo' de una forma creativa, indirecta o divertida. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir '(nombre_de_jugador) es sexy' de una forma creativa, indirecta o divertida. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir 'haz que deje de llorar el bebé' de una forma creativa, indirecta o divertida. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben nombrar una canción popular. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir un animal que empiece con la letra '(letra_al_azar)'. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir un plato de comida típico de algún país. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir una película de Disney. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben decir algo que comience con la letra '(letra_al_azar)'. Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben nombrar algo relacionado con el espacio (planetas, estrellas, etc.). Quien repita o se quede sin ideas, pierde.",
    "Por turnos deben nombrar un superhéroe. Quien repita o se quede sin ideas, pierde.",
    "Durante una ronda, cada vez que sonrías o te rías, debés beber.",
    "Durante una ronda debés jugar de espaldas. Si no querés, perdés.",
    "Durante una ronda, cuando quieras hablar, debés pronunciar una palabra cada 2 segundos. Por cada vez que falles, debés beber. (quiero… decir… que…)",
    "Durante una ronda, cuando quieras hablar, antes que nada debés decir 'te quiero (nombre_de_jugador)'. Por cada error debés beber.",
    "Durante una ronda deben jugar tomados de la mano con (nombre_de_jugador). Si no quieren o se sueltan, debés beber.",
    "Durante una ronda, ningún jugador puede mirarte a los ojos. Quien lo haga, debe beber.",
    "Durante una ronda debés hablar como si fueras un robot. Si no lo hacés, perdés.",
    "Durante una ronda, cada vez que alguien diga tu nombre, debés aplaudir. Si te olvidás de hacerlo, perdés.",
    "Durante una ronda debés imitar el acento de otro país. Si no lo hacés o te equivocás, perdés.",
    "Durante una ronda, no podés cruzar los brazos ni las piernas. Si lo hacés, perdés.",
    "Durante una ronda no podés usar palabras con más de tres sílabas. Si lo hacés, perdés.",
    "Durante una ronda, cada vez que hables, debés hacerlo cantando. Si no lo hacés, perdés.",
    "Debés girar la botella; a quien apunte, debe beber.",
    "Debés tomar un trago por cada alarma programada (activada o desactivada).",
    "Debés tomar un trago por cada grupo de WhatsApp que tengas.",
    "Debés sacarte una foto con (nombre_de_jugador) y ponerla de fondo de pantalla. Si te negás, debés beber.",
    "Debés escribir 'Quiero confesarte que te amo, siempre te amé y no sabía cómo decírtelo' a la última persona que te haya mandado un WhatsApp. Si te negás, debés beber.",
    "Debés hacer 5 flexiones en el lugar. Si no podés o te negás, perdés.",
    "Debés hacer un dibujo con los ojos cerrados y todos deben adivinar qué es. Si nadie lo adivina, perdés.",
    "Debés elegir una letra y (nombre_de_jugador) debe decir un país o animal que empiece con esa letra. La ronda sigue por la derecha; quien se quede sin ideas o repita, pierde.",
    "Debés decir una palabra que empiece con la inicial de (nombre_de_jugador). La ronda sigue por la derecha; quien se quede sin ideas o repita, pierde.",
    "Todos deben hacer 10 sentadillas. Quienes no las hagan, pierden.",
    "Debés elegir a (nombre_de_jugador). Ambos deben bailar sincronizadamente por 20 segundos. Si no lo logran, pierden.",
    "Debés bailar 'Unchained Melody' con (nombre_de_jugador) por 30 segundos. Si alguno se niega, pierden ambos.",
    "Debés armar una torre con objetos de la mesa. Si se cae antes de terminar, perdés.",
    "Tenés que contar un chiste. Si nadie se ríe, perdés.",
    "Tenés que inventar una canción de 10 segundos sobre un tema elegido por (nombre_de_jugador). Si no lo hacés, perdés.",
    "Tenés que buscar un objeto en la habitación que comience con la letra '(letra_al_azar)'. Si no lo encontrás en 30 segundos, perdés.",
    "Tenés que mirar a los ojos a (nombre_de_jugador) durante 20 segundos sin reírte. Si te reís, perdés.",
    "Tenés que actuar como un animal elegido por (nombre_de_jugador) durante 30 segundos. Si te negás, perdés.",
    "Tenés que hacer un sonido de animal cada vez que alguien te mire. Si te olvidás, perdés.",
    "Tenés que decir tres palabras que rimen entre sí. Si no podés, perdés.",
    "Tenés que crear un saludo nuevo para cada persona que te mire. Si repitís, perdés.",
    "Tenés que hacer una pose de yoga. Si no la hacés correctamente, perdés.",
    "Tenés que decir una cosa que harías si tuvieras un millón de dólares. Si no lo decís, perdés.",
    "Tenés que mencionar una película que consideres sobrevalorada. Si no lo decís, perdés.",
    "Todos los que sean más bajos que vos deben hacer 10 sentadillas. Quienes no las hagan, pierden.",
    "Todos deben levantar entre 1 y 5 dedos. No leas en voz alta: (Quienes hayan levantado un número par deben beber.)",
    "Todos deben levantar entre 1 y 5 dedos. No leas en voz alta: (Quienes hayan levantado un número impar deben beber.)",
    "Deben poner todos los teléfonos sobre la mesa y subirle el volumen a los mensajes. Al primero que le suene, pierde.",
    "Todos deben intentar adivinar el color de tus medias. Si nadie acierta, pierden.",
    "Todos deben imitar a un animal. No vale repetir, si alguien no lo hace, pierde.",
    "Todos deben compartir su última foto tomada. Si alguien se niega, pierde.",
    "Todos deben nombrar un personaje histórico. Si alguien repite o no sabe, pierde.",
    "Todos deben decir un país de Europa. Si alguien se queda sin ideas, pierde.",
    "Todos deben nombrar una ciudad de América del Sur. Si alguien repite o no sabe, pierde.",
    "Todos deben nombrar una película de terror. Si alguien repite o no sabe, pierde.",
    "Todos deben decir una marca de autos. Si alguien repite o no sabe, pierde.",
    "Todos deben nombrar un instrumento musical sin cuerdas. Si alguien repite o no sabe, pierde.",
    "Todos deben decir una fecha histórica importante. Si alguien repite o no sabe, pierde.",
    "Todos deben nombrar una flor. Si alguien repite o no sabe, pierde.",
    "Todos deben nombrar un videojuego clásico. Si alguien repite o no sabe, pierde.",
    "Todos deben contar qué harían si no pudieran vivir en una ciudad. Si alguien se queda sin ideas, pierde.",
    "Todos deben mencionar una película de los años 90. Si alguien repite o no sabe, pierde.",
    "Todos deben nombrar un cómic famoso. Si alguien repite o no sabe, pierde.",
    "Todos deben mencionar una comida típica de su país. Si alguien repite o no sabe, pierde.",
    "Todos deben mencionar un deporte que no tenga pelota. Si alguien repite o no sabe, pierde.",
    "Todos deben decir un dato curioso sobre un animal. Quien no lo diga, pierde.",
    "Durante una ronda todos deben pararse y menear de forma sensual antes de leer su reto en su turno.",
    "Durante una ronda no se puede decir 'si' ni 'no', quién y por cada vez que lo diga pierde.",
    "Por turnos deben decir diferentes cosas que no pueden faltar en una valija cuando te vas de viaje. Quien repite o se quede sin ideas, pierde.",
    "Debes decir el abecedario al revés en 20 segundos sin equivocarte.",
    "Durante una ronda toque la mesa con sus manos, pierde.",
    "Debes dejar que (nombre_de_jugador) cambie tu foto de perfil de whatsapp y debe permanecer lo que dure el juego.",
    "Debes ponerle me gusta, a la foto de la persona que elija (nombre_de_jugador) en instagram.",
    "Debes acariciar el mentón mirándolos a los ojos por 20 segundos a todos los que tengan barba.",
    "Por turnos deben decir cosas cosas que se dejan de hacer cuando la gente envejece, Si alguien repite o no sabe, pierde.",
    "Todos deben decir una cifra aproximada de cuántos habitantes hay en Mozambique, el que esté más lejos pierde.",
    "Tenes que decir algo bueno y algo malo de (nombre_de_jugador).",
    "Desafía a (nombre_de_jugador) a nombrar 6 animales sin repetir en 10 segundos. Si lo hace bien perdés vos.",
    "Sacate un selfie con el inodoro y subila al grupo de whatsapp que (nombre_de_jugador) decida.",
    "Durante dos rondas, a cada jugador que le saques una foto sin que se de cuenta pierde.",
    "Quien tenga una mascota que no sea gato o perro, elige quién pierde.",
    "Podes inflar tus cachetes cuando desees (puede ser más adelante) cuando lo hagas todos deben hacer lo mismo, el último en hacerlo pierde.",
    "¿De qué signo es (nombre_de_jugador)? si le erras perdés.",
    "Por turnos arranca diciendo 'abro el baúl' luego di una frase y termina 'cierro el baúl' Ejemplo: 'Abro el baúl pongo una remera, cierro el baúl' el que sigue 'abro el baúl pongo una remera, saco un gallo, cierro el baúl' quien se equivoque pierde.",
    "Debes escribir a tus ultimas 5 conversaciones de whatsapp la frase 'Tenemos que hablar…' debes leer en voz alta lo que te respondan. No puedes avisar que es un reto.",
    "Por turnos deben decir diferentes ventajas de tener los brazos de 10 metros. Quien repite o se queda sin ideas pierde.",
    "Todos deben hablar silenciosamente como si estuvieran en una biblioteca por 5 minutos, quien se olvida o no lo hace, pierde.",
    "Durante una ronda, tenes que repetir lo que diga (nombre_de_jugador).",
    "Por turnos deben decir diferentes ventajas de ser mujer. Quien repite o se queda sin ideas pierde.",
    "Por turnos deben decir diferentes ventajas de ser hombre. Quien repite o se queda sin ideas pierde.",
    "Por turnos deben decir diferentes ventajas de ser niño/a. Quien repite o se queda sin ideas pierde.",
    "Por turnos deben decir diferentes ventajas de ser adulto/a. Quien repite o se queda sin ideas pierde.",
    "Debes sacarle una foto a tu foto del documento y ponerla de perfil en tu whatsapp.",
    "Durante una ronda, debes colocarte una media como títere y utilizarla para hablar.",
    "Publica en instagram una foto que te saque (nombre_de_jugador) en este momento.",
    "Todos deben construir una historia en conjunto. (nombre_de_jugador) empieza diciendo una palabra, quien está a su izquierda debe repetir lo dicho y agregar una palabra (solo una), así hasta que alguien se equivoque.",
    "Por turnos deben decir diferentes cosas o lugares que se abren por la noche. Quien repite o se queda sin ideas pierde.",
    "La última persona en tocarte pierde.",
    "Desafía a (nombre_de_jugador) al 'Pan y Queso'.",
    "Durante una ronda, todos deben decir 'Te amo (nombre_de_jugador)' antes de leer el reto de su turno.",
    "Por turnos deben decir diferentes ingredientes para hacer un daiquiri. Quien repite o se queda sin ideas pierde.",
    "Hasta el fin del juego todos deben llamarte Willy. Quien se olvide por cada vez que lo haga pierde.",
    "Hasta el fin del juego tú y (nombre_de_jugador) intercambian sus nombres. Quien se olvide por cada vez que lo haga pierde.",
    "Desafía a (nombre_de_jugador) una pulseada china.",
    "Todos deben tomar 1 trago por cada vocal en su nombre completo.",
    "Debes cantarle el Feliz Cumpleaños al jugador más joven y hacerle el tirón de oreja.",
    "La primer persona en poner un objeto negro sobre la mesa decide quien pierde.",
    "Tenés que fingir por 30 segundos que estás dando a luz a un bebe.",
    "Por turnos deben decir el abecedario al revés, vos empezás con la Z. Quien se equivoca pierde."
];

//const castigos = ["Beber 1 trago", "Beber 2 tragos", "Beber 3 tragos", "Beber 4 tragos", "Beber 5 tragos", "Beber Fondo Blanco"];